### PR TITLE
feat: update of Plant UML rendering

### PR DESCRIPTION
**Pull request by CjHare**
Changing the puml rendering to use the WindRanger fork of Node-PlantUml, configured for recursive search when given a directory and generating svg files.

### CODE REVIEW

**Comment by bitparadigm** [comment]
LGTM, but do we want to have generated flow images included in the repo?

**Review by bitparadigm — APPROVED** [review]

**Review by shahankhatch — APPROVED** [review]
Thanks. Having the generated svgs will make it possible to deploy a basic ghpages documentation site.

**Comment by CjHare** [comment]
> but do we want to have generated flow images included in the repo?

🤷 
The rendering need to go somewhere, either the repo that contains the `puml` or another. 

Generating the renders requires a Java JRE install, which is a decent case for not leaving them as a generate it yourself (also as svg can be viewed in a browser, you can view the sequence diagrams when browsing the code)

**Comment by shahankhatch** [comment]
If we turn the generation into its own repo/dependency, we can then include it as a dev dependency for the generation and development process (i.e., committing updated svgs when the puml changes).

**Comment by CjHare** [comment]
>If we turn the generation into its own repo/dependency, we can then include it as a dev dependency for the generation and development process (i.e., committing updated svgs when the puml changes).

Interesting idea.

There exists GitHub actions for generating the rending of puml files, these could be used as a template for that (not sure on the process tie in for create PR ...but dependency bot achieves it, so it must be possible and probably copiable).

Deciding on whether all the WindRanger SVGs are kept in their own repo, probably is determined by the target audience of them.
I see the value in a sequence diagram repo 👍

**Pull request merged**
